[package]
name = "wasmer-exports"
version = "0.1.0"
authors = ["Thiago Machado <thiago@keyko.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.0"
wasmer = "2.0.0"
structopt = "0.3.0"
glob = "0.3.0"